### ISSUE TITLE
US11: Assign presentations to a room

### ISSUE THREAD

**Issue by ParleyMartins** [AUCSC/sac#11]
As an admin, I want to be able to assign presentations to a room, so that I do not book too many presentations in one room.

**Given** I am on the schedule page
**When** I match a presentation to a room
**Then** that presentation should be added to that room

**Comment by agkaliel** [comment]
https://github.com/bevacqua/dragula

**Comment by ParleyMartins** [comment]
https://laravel.com/docs/5.2/elixir
