### ISSUE TITLE
Upon presentation edit/deletion, change redirect.

### ISSUE THREAD

**Issue by agkaliel** [AUCSC/sac#33]
Currently, any time we submit/edit/delete a presentation, we get redirected to the professors home page, with the course collapsed.  It would be nice if the expanded course remained open.

**Comment by ParleyMartins** [comment]
We need javascript for that. It happens because after the post request, the controller redirects to that page again, therefore the entire page is reloaded. The collapse default behaviour is closed when the page is reloaded.
